version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["minor", "major"]  # Ignore minor and major version updates
    groups:
      patch:
        update-types:
          - "patch"  # Includes only patch version updates
      security-updates:
        update-types:
          - "security"  # Includes only security updates