---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:  # Grouping for minor and patch updates.
        applies-to: "version-updates"  # Applies this group to regular version updates.
        update-types:
          - "minor"  # Includes minor version updates.
          - "patch"  # Includes patch version updates.
      security-updates:  # A separate group specifically for security updates.
        applies-to: security  # Only applies to security-related updates.
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
