version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["minor", "major"]  # Ignore minor and major version updates
    groups:groups:
      patch-updates:
        patterns:
          - "*"  # Groups all dependencies together
        update-types:
          - "patch"
      security-updates:
        patterns:
          - "*"  # Groups all security updates