---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch: # A separate group specifically for patch updates.
        applies-to: version-updates # Applies this group to regular version updates.
        update-types:
          - "patch" # Includes patch version updates.
      security-updates:  # A separate group specifically for security updates.
        applies-to: security-updates
        patterns:
          - "*"
